// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVdumOQLC__VZb59SX2GLADOUM2r3Ph1M',
    appId: '1:501893544696:web:ef9577f195847ee8c3d90d',
    messagingSenderId: '501893544696',
    projectId: 'paradise-bac82',
    authDomain: 'paradise-bac82.firebaseapp.com',
    databaseURL: 'https://paradise-bac82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paradise-bac82.appspot.com',
    measurementId: 'G-53F9EN91S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuH1Rl6Zu_NNGEjJk47ci9X8ZAfa1yvTo',
    appId: '1:501893544696:android:cb93f6cbec5d49adc3d90d',
    messagingSenderId: '501893544696',
    projectId: 'paradise-bac82',
    databaseURL: 'https://paradise-bac82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paradise-bac82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqSXoNreOpxF41qkseyWLw_a46Aww_EZM',
    appId: '1:501893544696:ios:f9d39fc53a1bc3a8c3d90d',
    messagingSenderId: '501893544696',
    projectId: 'paradise-bac82',
    databaseURL: 'https://paradise-bac82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paradise-bac82.appspot.com',
    iosClientId: '501893544696-dvlsbs7duhne135l7l93j7h3mnrb5l9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.paradise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqSXoNreOpxF41qkseyWLw_a46Aww_EZM',
    appId: '1:501893544696:ios:f9d39fc53a1bc3a8c3d90d',
    messagingSenderId: '501893544696',
    projectId: 'paradise-bac82',
    databaseURL: 'https://paradise-bac82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paradise-bac82.appspot.com',
    iosClientId: '501893544696-dvlsbs7duhne135l7l93j7h3mnrb5l9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.paradise',
  );
}
